# Orders with zero unit price

## 1.0 Import nececssary lbraries

In [1]:
# Data analysis
import pandas as pd

# Directory
from pathlib import Path

## 2.0 Paths

In [2]:
# Current directory
CURRENT_DIR = Path.cwd()

# Path to main folder
PROJECT_ROOT = CURRENT_DIR.parent.parent

# Path to folders
ZERO_PRICE_PATH = PROJECT_ROOT/"data"/"processed"/"zero_price.csv"

## 3.0 Load dataset

In [3]:
zero_price = pd.read_csv(ZERO_PRICE_PATH)
zero_price

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536414,22139,RETROSPOT TEA SET CERAMIC 11 PC,56,2010-12-01 11:52:00,0.0,536414I,United Kingdom,0.0
1,536546,22145,CHRISTMAS CRAFT HEART STOCKING,1,2010-12-01 14:33:00,0.0,536546I,United Kingdom,0.0
2,536547,37509,NEW ENGLAND MUG W GIFT BOX,1,2010-12-01 14:33:00,0.0,536547I,United Kingdom,0.0
3,536553,37461,FUNKY MONKEY MUG,3,2010-12-01 14:35:00,0.0,536553I,United Kingdom,0.0
4,536765,84952C,MIRROR LOVE BIRD T-LIGHT HOLDER,19,2010-12-02 14:43:00,0.0,536765I,United Kingdom,0.0
...,...,...,...,...,...,...,...,...,...
1154,581211,22142,check,14,2011-12-07 18:36:00,0.0,581211I,United Kingdom,0.0
1155,581234,72817,SET OF 2 CHRISTMAS DECOUPAGE CANDLE,27,2011-12-08 10:33:00,0.0,581234I,United Kingdom,0.0
1156,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,581406I,United Kingdom,0.0
1157,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,581406I,United Kingdom,0.0
1158,581408,85175,CACTI T-LIGHT CANDLES,20,2011-12-08 14:06:00,0.0,581408I,United Kingdom,0.0

In [4]:
# Shape of dataset
shape = zero_price.shape
print(f'Number of rows: {shape[0]}')
print(f'Number of columns: {shape[1]}')

Number of rows: 1159
Number of columns: 9

## 4.0 Distinct products that had zero unit price

In [5]:
# Number of distinct products
total_products = zero_price['Description'].nunique()

print(f'Total distinct products : {total_products}')

Total distinct products : 636

In [6]:
# Number of times product has had zero unit price
distinct_products = zero_price.groupby('Description').agg(
    Count = ('Description', 'count'),
    TotalRevenue = ('TotalPrice', 'sum')
).reset_index().sort_values('Count', ascending=False).reset_index(drop=True)

#pd.set_option('display.max_rows', None) # To see all rows

print(distinct_products)

                             Description  Count  TotalRevenue
0                                  check     39           0.0
1                                  found     25           0.0
2                             adjustment     14           0.0
3             FOLKART HEART NAPKIN RINGS      9           0.0
4          FRENCH BLUE METAL DOOR SIGN 1      9           0.0
..                                   ...    ...           ...
631             for online retail orders      1           0.0
632                            found box      1           0.0
633  incorrectly credited C550456 see 47      1           0.0
634          4 TRADITIONAL SPINNING TOPS      1           0.0
635       4 BURGUNDY WINE DINNER CANDLES      1           0.0

[636 rows x 3 columns]

## 5.0 Total products

In [7]:
total_quantity = zero_price['Quantity'].sum()
total_quantity

np.int64(72496)

## 6.0 Lower case descriptions

In [8]:
lower_case = zero_price[zero_price['Description'].str.islower()]
lower_case

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
5,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,536941I,United Kingdom,0.0
6,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,536942I,United Kingdom,0.0
72,537639,22734,amazon,30,2010-12-07 15:29:00,0.0,537639I,United Kingdom,0.0
101,538348,22734,amazon,30,2010-12-10 14:59:00,0.0,538348I,United Kingdom,0.0
105,538873,22734,amazon sales,20,2010-12-14 15:13:00,0.0,538873I,United Kingdom,0.0
...,...,...,...,...,...,...,...,...,...
1140,580376,22606,check,8,2011-12-02 17:49:00,0.0,580376I,United Kingdom,0.0
1143,580549,84876B,found,66,2011-12-05 09:54:00,0.0,580549I,United Kingdom,0.0
1145,580586,21804,dotcom,4,2011-12-05 10:34:00,0.0,580586I,United Kingdom,0.0
1151,581202,23404,check,41,2011-12-07 18:30:00,0.0,581202I,United Kingdom,0.0
1154,581211,22142,check,14,2011-12-07 18:36:00,0.0,581211I,United Kingdom,0.0

In [9]:
# Unique descriptions that are in lowercase
distinct_lower = lower_case['Description'].unique()
distinct_lower

array(['amazon', 'amazon sales', 'found', 'thrown away',
       'wrongly sold (22719) barcode',
       'rcvd be air temp fix for dotcom sit',
       'did  a credit  and did not tick ret', 'adjustment', 'returned',
       'mailout ', 'mailout', 'on cargo order',
       'to push order througha s stock was ', 'came coded as 20713',
       'alan hodge cant mamage this section', 'dotcom', 'test',
       'taig adjust', 'allocate stock for dotcom orders ta',
       'add stock to allocate online orders', 'for online retail orders',
       'found box', 'damaged', 'website fixed', 'michel oops',
       'wrongly coded 20713', 'wrongly marked 23343',
       'wrongly coded 23343', 'check', 'wrongly marked',
       'had been put aside', 'amazon adjust', 'dotcomstock',
       'dotcom adjust', 'check?'], dtype=object)

- They seem to be errrors that were adjusted. 
- The descriptions are not standardized.